language: node_js
node_js:
  - 14
cache:
  directories:
  - node_modules
script:
  - npm run build
  - touch _static/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  on:
    branch: main